# Development MongoDB instance
# For local development only - not for production use

services:
  mongodb:
    image: mongo:8
    container_name: bsv-tracker-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bsv_tracker
    volumes:
      - mongodb_dev_data:/data/db

volumes:
  mongodb_dev_data:
    driver: local
